In [ ]:
!pip install pygad

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.8/80.8 kB 1.5 MB/s eta 0:00:00


In [ ]:
import pygad
import numpy
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
def func_adapt(tab, A=1):
    n = len(tab)
    help = tab*2*np.pi
    help = A*np.cos(help)
    sum = ((tab*tab)-help).sum()
    return -(A*n+sum)

In [ ]:
n = 3
x = np.linspace(-4,4,n*100)
x = np.array_split(x,100)
y = [func_adapt(xx) for xx in x]
# plt.rcParams['figure.figsize'] = (6,6)
# fig = plt.figure()
# ax = fig.add_subplot(projection='3d')
# surface = ax.plot_surface(x[0::3],x[1::3], x[2::3], cmap='coolwarm')
# ax.plot(x,y)
# plt.show()

In [ ]:
def fitness_func(ga_insance, solution, solution_idx):
  return func_adapt(solution[0:3])

In [ ]:
last_fitness=0
def on_generation(ga_instance):
  global last_fitness
  print(f"Generation: {ga_instance.generations_completed}")
  print(f"Fitness: {ga_instance.best_solution(pop_fitness=ga_instance.last_generation_fitness)[1]}")
  print(f"Change: {ga_instance.best_solution(pop_fitness=ga_instance.last_generation_fitness)[1] - last_fitness}")
  print()
  last_fitness = ga_instance.best_solution(pop_fitness=ga_instance.last_generation_fitness)[1]

In [ ]:
ga_instance = pygad.GA(num_generations=50,
                       num_parents_mating=10,
                       sol_per_pop=15,
                       num_genes=3,

                       fitness_func=fitness_func,
                       crossover_type='single_point',
                       parent_selection_type='rws',
                       mutation_by_replacement=True,

                       mutation_type='random',
                       mutation_percent_genes=2,
                       on_generation=on_generation)

/usr/local/lib/python3.10/dist-packages/pygad/pygad.py:748: UserWarning: The percentage of genes to mutate (mutation_percent_genes=2) resutled in selecting (0) genes. The number of genes to mutate is set to 1 (mutation_num_genes=1).
If you do not want to mutate any gene, please set mutation_type=None.
  warnings.warn(f"The percentage of genes to mutate (mutation_percent_genes={mutation_percent_genes}) resutled in selecting ({mutation_num_genes}) genes. The number of genes to mutate is set to 1 (mutation_num_genes=1).\nIf you do not want to mutate any gene, please set mutation_type=None.")


In [ ]:
# print(ga_instance.population)

In [ ]:
ga_instance.run()

Generation: 1
Fitness: -5.094654681251802
Change: -5.094654681251802

Generation: 2
Fitness: -4.461800536334012
Change: 0.6328541449177898

Generation: 3
Fitness: -2.3251728430240535
Change: 2.1366276933099586

Generation: 4
Fitness: -2.2591565290127296
Change: 0.0660163140113239

Generation: 5
Fitness: -2.2591565290127296
Change: 0.0

Generation: 6
Fitness: -2.2591565290127296
Change: 0.0

Generation: 7
Fitness: -2.2591565290127296
Change: 0.0

Generation: 8
Fitness: -2.2591565290127296
Change: 0.0

Generation: 9
Fitness: -2.1363022292968203
Change: 0.12285429971590922

Generation: 10
Fitness: -1.0744773939301866
Change: 1.0618248353666337

Generation: 11
Fitness: -1.0744773939301866
Change: 0.0

Generation: 12
Fitness: -1.0744773939301866
Change: 0.0

Generation: 13
Fitness: -1.0744773939301866
Change: 0.0

Generation: 14
Fitness: -1.0744773939301866
Change: 0.0

Generation: 15
Fitness: -1.0744773939301866
Change: 0.0

Generation: 16
Fitness: -0.695827982401847
Change: 0.378649411528

In [ ]:
# Wypisanie najlepszych rozwiazan
solution, solution_fitness, solution_idx = ga_instance.best_solution()
print(f"Parametery najlepszego rozwiązania : {solution}")
print(f"Wartosc dla najlepszego rozwiazania = {solution_fitness}")

Parametery najlepszego rozwiązania : [-0.02442483  0.06322485  0.03744338]
Wartosc dla najlepszego rozwiazania = -0.12316875179182585


In [ ]:
print(ga_instance.population)

[[-0.00372605 -0.18231157  0.06043913]
 [-0.33441576  0.30194785  3.55904986]
 [-0.33441576  0.80260493  0.53563231]
 [-0.02442483  0.30765016 -0.61515035]
 [-0.02442483  0.06322485  0.03744338]
 [ 0.51413055 -0.26924089  3.55904986]
 [ 0.51413055  0.13970178  0.65588614]
 [ 0.5213933   0.38823435  0.26669964]
 [ 0.30479905  0.38823435  3.55904986]
 [-0.18567782  0.39740246  0.39951182]
 [-0.49242362 -0.43960209  3.55904986]
 [ 0.92797839  0.28976012  3.55904986]
 [-0.33441576  0.80260493  0.05481499]
 [-0.33441576  0.3954212  -0.61515035]
 [-0.73118186  0.39740246  3.55904986]]
